trigger:
  batch: true
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: _variables.yml

stages:
  - stage: StageJobInstallLintBuildTest
    displayName: 'Install, Lint, Build and Test'
    jobs:
      - job: JobInstallLintBuildTest
        displayName: 'Build'
        steps:
          - template: _install-lint-build.yml

  - stage: StageManualProdDeploy
    displayName: 'PROD Deploy Approval: Playground Angular'
    dependsOn: StageJobInstallLintBuildTest
    jobs:
      - job: JobApproval
        displayName: 'Approval for Prod Deploy'
        pool: server
        steps:
          # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-validation-v0?view=azure-pipelines
          - task: ManualValidation@0
            inputs:
#              notifyUsers: |
#                user@example.com
              instructions: 'On Approval, performs a PROD Deploy'
#              onTimeout: 'resume'

  - template: _stage_deploy.yml
    parameters:
      env: 'prod'
      ARTIFACT_NAME: '$(ARTIFACT_NAME_PROD)'
      dependsOn: 'StageManualProdDeploy'

  - template: _stage_deploy.yml
    parameters:
      env: 'uat'
      ARTIFACT_NAME: '$(ARTIFACT_NAME_UAT)'
      dependsOn: 'StageJobInstallLintBuildTest'
