trigger:
  - none

variables:
  - name: APP_NAME
    value: 'playground-angular'
  # defined in the Pipeline Library variable group
  # see: https://learn.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml
#  - group: DEFAULT_VARIABLE_GROUP

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '16.19.x'

  - script: npm ci
    displayName: 'Install Node Packages'

  - script: npm run build
    displayName: 'Angular build'

  - script: npm run test:ci
    displayName: 'Angular Test'

  - script: npm run lint
    displayName: 'Angular Lint'

  - task: CopyFiles@2
    displayName: 'Copying files from dist folder'
    inputs:
      Contents: |
        dist/$(APP_NAME)
      TargetFolder: $(Build.ArtifactStagingDirectory)

#  - task: AzureStaticWebApp@0
#    inputs:
#      app_location: '/dist/$(APP_NAME)/'
#      skip_app_build: true
#      skip_api_build: true
#      is_static_export: true
#      # this is the directory where the pipeline will look for the staticwebapp.config.json file
#      config_file_location: '/azure-pipelines/'
#      # this variable comes from the pipeline library variable group
#      azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
